version: '3.8'
services:
  kge:
    build: 
      context: .
    volumes:
      - ./main.py:/kge/main.py
      - ./dbpedia50-complex.yaml:/kge/examples/dbpedia50-complex.yaml
      - ./results:/kge/local/experiments/main