version: "3.8"
services:
  kge:
    build:
      context: .
    volumes:
      - ./main.py:/kge/main.py
      - ./train.yaml:/kge/examples/train.yaml
      - ./rescal.yaml:/kge/examples/rescal.yaml
      - ./results:/kge/local/experiments/main
